version: "3.9"

services:
  test-tracker-zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181
    restart: unless-stopped
    networks:
      - test-tracker-backend

  test-tracker-kafka:
    image: wurstmeister/kafka
    ports:
      - 9092
    depends_on:
      - test-tracker-zookeeper
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: test-tracker-kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: test-tracker-zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: topic-tracking-events:1:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - test-tracker-backend

  test-tracker-clickhouse:
    image: yandex/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: always
    networks:
      - test-tracker-backend
    ports:
      - 8123
    depends_on:
      - test-tracker-kafka
    volumes:
      - ./scripts/ch:/docker-entrypoint-initdb.d
    environment:
      CLICKHOUSE_DB: tracker
      MYSQL_PORT: 9004

  test-tracker-postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432
    volumes:
      - ./scripts/pg:/docker-entrypoint-initdb.d
    networks:
      - test-tracker-backend
    environment:
      POSTGRES_PASSWORD: development
      POSTGRES_DB: tracker
      PGDATA: /var/lib/postgresql/data/tracker/

  test-tracker-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/tracker/src
      - ./tests:/tracker/tests
      - /tracker/node_modules
    command: sh -c "npm run test"
    ports:
      - 8888
    networks:
      - test-tracker-backend
      - test-tracker-api
    depends_on:
      - test-tracker-kafka
      - test-tracker-clickhouse
      - test-tracker-postgres
    environment:
      NODE_ENV: test
      API_SERVER_PORT: 8888
      PG_DATABASE_URI: postgres://postgres:development@test-tracker-postgres/tracker
      CH_DATABASE_URL: http://test-tracker-clickhouse
      CH_DATABASE_NAME: tracker
      CH_DATABASE_PORT: 8123
      KAFKA_SERVER: test-tracker-kafka:9092
      KAFKA_TOPIC_TRACKING_EVENTS: topic-tracking-events

networks:
  test-tracker-backend:
    name: test-tracker-backend
    driver: bridge

  test-tracker-api:
    name: test-tracker-api
    driver: bridge
